image: ubuntu

stack: node 10

environment:
  AWS_REGION: eu-west-1
  AWS_USER_ACCESS_KEY_ID:
    secure: 0rzhCauQXAU91jsjzybV2CEenA/maZOO2/1ZRnGkOGw=
  AWS_USER_SECRET_ACCESS_KEY:
    secure: 5BAsRA0GxhV0/vrBmqNJolXHryl1GqWxu+4sJi4GVStTuskayDySfVzk8l47g0ou
  AWS_ROLE_ACCESS_KEY_ID:
    secure: lmPK0e+6loeeq9IKSJ/2bQECaF8Bc7vH0aMbjzpZhAw=
  AWS_ROLE_SECRET_ACCESS_KEY:
    secure: EgRzP/XvepgtaUC/2k1QWwt6Vk6IRwOknlk/EOC2Q9G1QXQIc3QLUKdTAo39k20o
  AWS_ROLE_ARN:
    secure: CVjaIRrwBKMLa+ZIqgA4E4oiK9sUOGZncU78nup5xam1Lrl0RQgOTiEqTlfonNKP
  AWS_API_GATEWAY_URL:
    secure: wrN4wFxDowt29PJb+N1NEfFAqL1YcPjuclvv/4STXbKj+L/jYreQf0z6jg4yc9Ybe0ixJcwhf1Z64H2eZgjoew==
  CODECOV_TOKEN:
    secure: 8KH9Y0pwlpZODSh7oItr7AJ4u2cr/TB9ir2TckofpZJHAKtUhhWyihjPcRHf1M34

build_script:
  - ./build/build.sh

test: off

artifacts:
  - path: ./artifacts/*.nupkg
    name: NuGet

deploy:
  - provider: GitHub
    release: Release ${APPVEYOR_REPO_TAG_NAME}
    description: TODO
    auth_token:
      secure: de2wnJZf6k7NY0XriDpf9BkrQ4MR5ZfDDWMM+H/K4OK3w0GpuJAMRj5PrO6tKu0K
    artifact: /.*\.nupkg/
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    api_key:
      secure: uahkVS8ro53iDcbd2Hie8ofpUYvJ6tlR+mss0vTEp5tM6zXqDkhJF4iFKeZCvepD
    skip_symbols: false
    on:
      APPVEYOR_REPO_TAG: true
